### ISSUE TITLE
Nuove voci per "scelta contraente"

### ISSUE THREAD

**Issue by dgardina** [provinciadicremona/AVCP-Xml#16]
Buongiorno,
un utente ci segnala che nella procedura di richiesta di uno SMART CIG vengono fuori ora delle nuove voci per la "scelta contraente".
Vi risulta che sia cambiata la normativa? L'applicazione sarà aggiornata di conseguenza o si possono aggiungere a mano nella relativa tabella? E, infine, il tracciato inviato ad ANAC entro fine gennaio verrà riconosciuto come regolare anche se dovessero essere scelte queste nuove voci?
Grazie!

![CIG_01](https://user-images.githubusercontent.com/22657720/65955151-ca56ae00-e447-11e9-966f-3b0e12c8df33.png)
![CIG_02](https://user-images.githubusercontent.com/22657720/65955153-ca56ae00-e447-11e9-8115-c3f82c058086.png)

**Comment by giannibassiniprovincia** [comment]
Buongirno,
indipendentemente dal fatto che abbia aggiornato il programma alla nuova versione presente su github, può aggiungere le nuove voci seguendo le istruzioni che trova qui:
https://github.com/provinciadicremona/AVCP-Xml#aggiungere-le-nuove-modalit%C3%A0-di-scelta-del-contraente

In sostanza si tratta di modificare la tabella del db e sostituire il vecchio file di validazione TypesL190.xsd con quello nuovo fornito da ANAC.

Per qualsiasi chiarimento resto a disposizione.

Cordiali saluti.


-----------------------------------------
Claudio Roncaglio
Ufficio per le Relazioni con il Pubblico
della Provincia di Cremona 
C.so Vittorio Emanuele II,17
tel. +39 0372 406247 fax +39 0372 406301
-----------------------------------------

----- Messaggio originale -----
Da: "Diego Gardina" <notifications@github.com>
A: "provinciadicremona/AVCP-Xml" <AVCP-Xml@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Inviato: Martedì, 1 ottobre 2019 12:37:43
Oggetto: [provinciadicremona/AVCP-Xml] Nuove voci per "scelta contraente" (#16)

Buongiorno,

un utente ci segnala che nella procedura di richiesta di uno SMART CIG vengono fuori ora delle nuove voci per la "scelta contraente".

Vi risulta che sia cambiata la normativa? L'applicazione sarà aggiornata di conseguenza o si possono aggiungere a mano nella relativa tabella? E, infine, il tracciato inviato ad ANAC entro fine gennaio verrà riconosciuto come regolare anche se dovessero essere scelte queste nuove voci?

Grazie!



![CIG_01](https://user-images.githubusercontent.com/22657720/65955151-ca56ae00-e447-11e9-966f-3b0e12c8df33.png)

![CIG_02](https://user-images.githubusercontent.com/22657720/65955153-ca56ae00-e447-11e9-8115-c3f82c058086.png)





-- 

You are receiving this because you are subscribed to this thread.

Reply to this email directly or view it on GitHub:

https://github.com/provinciadicremona/AVCP-Xml/issues/16

**Comment by ClaudioRoncaglio** [comment]
Ok, adesso devo capire perché se rispondo io, viene fuori il messaggio come spedito da @giannibassiniprovincia ...

**Comment by dgardina** [comment]
Prima di aprire questa issue avevo controllato sul sito di ANAC e il file TypesL190.xsd  è in linea con quanto attualmente implementato nella vostra applicazione (che ho aggiornato all'ultima versione qui disponibile).
La lista delle voci di scelta contraente inviatami dall'utente appare solo nel momento in cui viene richiesto un CIG.. per quello chiedevo se ci fossero novità normative e applicative in vista..

**Comment by ClaudioRoncaglio** [comment]
Mi scusi ma non avevo guardato con attenzione l'elenco che appare nelle immagini allegate.
In effetti ci sono molte più voci di quelle contenute nell'aggiornamento del 21 gennaio, ma non saprei dirle se e quando si tradurranno in un ulteriore modifica al programma e neanche come possano essere "tradotte", usando quelle attualmente disponibili, per compilare la comunicazione relativa al 2019.  

Sono andato a consultare il sito dell'ANAC ma non ho trovato nessuna novità; a questo punto non so neanch'io cosa pensare.

**Comment by dgardina** [comment]
Restiamo in attesa di vedere se ci saranno ulteriori comunicazioni in futuro... Intanto grazie per la risposta!
