### ISSUE TITLE
Colelgamento azienda aggiudicataria su gara

### ISSUE THREAD

**Issue by cedgarbagnate** [provinciadicremona/AVCP-Xml#33]
Non si riesce ad inserire il partecipante alla gara.
Nella fattispecie la pratica è CIG. Z7F254C0B6 e l'aziendqa aggiudicataria è Colombo Giardini Srl
Se inserisco un altro aggiudicatario funziona, ho provato a modificare anche i dati di Colombo Giardini Srl ma non c’è verso.
Quando si da conferma dopo aver selezionato il partecipante la schermata diventa bianca e non fa più nulla.
Lo stesso aggiudicatario è stato utilizzato in altre pratiche senza problemi.
Ho provato anche da diversi browser ma nulla!!!!
Entro domani mattina dobbiamo inviare il file XML

**Come riprodurlo:**
Indicaci passo per passo come replicare il bug.
1. Vai qui '...'
2. Clicca su '....'
3. Etc...
4. Ecco l'errore.

**Screenshots**
Se possibile, aggiungi degli screenshot per mostrarci meglio il bug.

**Informazioni sull'installazione del programma AVCP-Xml:**
 - Versione di AVCP-Xml [e.g. v0.8.11]
 - Sistema Operativo: [ad es. Linux, Windows, etc..]
 - Versione di Apache
 - Versione di MySQL
 - Versione di PHP

**Aggiungi il log degli errori**
Se possibile, aggiungi la parte pertinente del log degli errori di apache (tipicamente, sotto linux si trova in /var/log/apache2/error.log)

**Comment by ProvinciaCremona** [comment]
Salve, 
per saperne di più e poterle dire qualcosa di utile dovrei vedere il log degli errori di apache, in ogni caso, visto che la ditta è già stata usata in altre gare e non ha dato problemi, le consiglio di provare ad eliminare la gara in questione e provare a reinserirla da capo.

Mi faccia sapere se così risolve e in caso contrario, provi a dare un'occhiata ai log.


-----------------------------------------
Claudio Roncaglio
Ufficio per le Relazioni con il Pubblico
della Provincia di Cremona 
C.so Vittorio Emanuele II,17
tel. +39 0372 406247 fax +39 0372 406301
-----------------------------------------

----- Messaggio originale -----
Da: "cedgarbagnate" <notifications@github.com>
A: "provinciadicremona" <AVCP-Xml@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Inviato: Giovedì, 30 gennaio 2020 10:15:58
Oggetto: [provinciadicremona/AVCP-Xml] Colelgamento azienda aggiudicataria su gara (#33)

Non si riesce ad inserire il partecipante alla gara.

Nella fattispecie la pratica è CIG. Z7F254C0B6 e l'aziendqa aggiudicataria è Colombo Giardini Srl

Se inserisco un altro aggiudicatario funziona, ho provato a modificare anche i dati di Colombo Giardini Srl ma non c’è verso.

Quando si da conferma dopo aver selezionato il partecipante la schermata diventa bianca e non fa più nulla.

Lo stesso aggiudicatario è stato utilizzato in altre pratiche senza problemi.

Ho provato anche da diversi browser ma nulla!!!!

Entro domani mattina dobbiamo inviare il file XML



**Come riprodurlo:**

Indicaci passo per passo come replicare il bug.

1. Vai qui '...'

2. Clicca su '....'

3. Etc...

4. Ecco l'errore.



**Screenshots**

Se possibile, aggiungi degli screenshot per mostrarci meglio il bug.



**Informazioni sull'installazione del programma AVCP-Xml:**

 - Versione di AVCP-Xml [e.g. v0.8.11]

 - Sistema Operativo: [ad es. Linux, Windows, etc..]

 - Versione di Apache

 - Versione di MySQL

 - Versione di PHP

 - Browser [e.g. chrome, safari]



**Aggiungi il log degli errori**

Se possibile, aggiungi la parte pertinente del log degli errori di apache (tipicamente, sotto linux si trova in /var/log/apache2/error.log)





-- 

You are receiving this because you are subscribed to this thread.

Reply to this email directly or view it on GitHub:

https://github.com/provinciadicremona/AVCP-Xml/issues/33

**Comment by cedgarbagnate** [comment]
Di seguito troverete i log richiesti
[Thu Jan 30 10:40:40.595375 2020] [php7:error] [pid 28800] [client 93.57.27.68:51473] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_error() in /var/www/avcp/AVCP_GARMIL/site/app/model/garaPartecipanti.php:207 Stack trace: #0 /var/www/avcp/AVCP_GARMIL/site/app/controller/garaController.php(25): require_once() #1 /var/www/avcp/AVCP_GARMIL/site/app/controller/indexController.php(24): require_once('/var/www/avcp/A...') #2 /var/www/avcp/AVCP_GARMIL/site/index.php(45): require_once('/var/www/avcp/A...') #3 {main}   thrown in /var/www/avcp/AVCP_GARMIL/site/app/model/garaPartecipanti.php on line 207, referer: http://xml.comune.garbagnate-milanese.mi.it/?mask=ditta&do=cercaDitta&id=2903


Informazioni sull'installazione del programma AVCP-Xml:

    Versione di AVCP-Xml [0.9.0]
    Sistema Operativo: [Linux]
    Versione di Apache [Server version: Apache/2.4.25 (Debian)]
    Versione di MySQL [Ver 15.1 Distrib 10.1.37-MariaDB]
    Versione di PHP [PHP 7.3.1]
    Browser [tutti]

**Comment by ProvinciaCremona** [comment]
Ok, 
qui c'è un mio sbaglio nella stampa dell'errore; sostituisca il file app/model/garaPartecipanti.php con quello che le invio e riprovi ad inserire la ditta.
Dovrebbe fallire ancora, ma almeno adesso vedrà il perché. 

Mi faccia sapere cosa le dice e mi rimandi il log col nuovo errore.

PS - Ha provato a cancellare la gara e a reinserirla?


-----------------------------------------
Claudio Roncaglio
Ufficio per le Relazioni con il Pubblico
della Provincia di Cremona 
C.so Vittorio Emanuele II,17
tel. +39 0372 406247 fax +39 0372 406301
-----------------------------------------

----- Messaggio originale -----
Da: "cedgarbagnate" <notifications@github.com>
A: "provinciadicremona" <AVCP-Xml@noreply.github.com>
Cc: "ProvinciaCremona" <github@provincia.cremona.it>, "Comment" <comment@noreply.github.com>
Inviato: Giovedì, 30 gennaio 2020 11:15:48
Oggetto: Re: [provinciadicremona/AVCP-Xml] Colelgamento azienda aggiudicataria su gara (#33)

Di seguito troverete i log richiesti
[Thu Jan 30 10:40:40.595375 2020] [php7:error] [pid 28800] [client 93.57.27.68:51473] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_error() in /var/www/avcp/AVCP_GARMIL/site/app/model/garaPartecipanti.php:207 Stack trace: #0 /var/www/avcp/AVCP_GARMIL/site/app/controller/garaController.php(25): require_once() #1 /var/www/avcp/AVCP_GARMIL/site/app/controller/indexController.php(24): require_once('/var/www/avcp/A...') #2 /var/www/avcp/AVCP_GARMIL/site/index.php(45): require_once('/var/www/avcp/A...') #3 {main}   thrown in /var/www/avcp/AVCP_GARMIL/site/app/model/garaPartecipanti.php on line 207, referer: http://xml.comune.garbagnate-milanese.mi.it/?mask=ditta&do=cercaDitta&id=2903


Informazioni sull'installazione del programma AVCP-Xml:

    Versione di AVCP-Xml [0.9.0]
    Sistema Operativo: [Linux]
    Versione di Apache [Server version: Apache/2.4.25 (Debian)]
    Versione di MySQL [Ver 15.1 Distrib 10.1.37-MariaDB]
    Versione di PHP [PHP 7.3.1]
    Browser [tutti]

**Comment by cedgarbagnate** [comment]
Grazie mille.

Con l’errore abbiamo scoperto il problema.

 

Cordiali saluti

 

Veronica Malara

Servizio Innovazione Tecnologica

Comune di Garbagnate Milanese

Cel. 346.17 21 562

Tel. 02.78618.236

www.comune.garbagnate-milanese.mi.it

 

Questo messaggio di posta elettronica ed ogni suo eventuale allegato possono contenere informazioni di carattere privato o confidenziale, rivolte esclusivamente ai destinatari sopra indicati.

Se non siete quindi tra i corretti destinatari o se avete ricevuto erroneamente questo messaggio, siete pregati di rispondere immediatamente al mittente segnalando l’accaduto e successivamente cancellare quanto ricevuto, compresi gli eventuali allegati. A tal riguardo, Vi rendiamo noto che l’utilizzo, la divulgazione, la copia o la distribuzione, anche parziale di questo messaggio, costituiscono violazione dell’obbligo di non prendere cognizione della corrispondenza tra altri soggetti, sia ai sensi

dell’art.616 del Codice Penale, sia ai sensi del Regolamento EU 679/2016 ed espongono quindi il responsabile alle relative conseguenze. Si evidenzia, infine, che le informazioni o le opinioni espresse in questo messaggio o all’interno dei suoi eventuali allegati, rappresentano esclusivamente il punto di vista del mittente, che non necessariamente coincide con gli atti ufficiali del Comune di Garbagnate Milanese.

 

Da: ProvinciaCremona [mailto:notifications@github.com] 
Inviato: giovedì 30 gennaio 2020 11:28
A: provinciadicremona/AVCP-Xml
Cc: cedgarbagnate; Author
Oggetto: Re: [provinciadicremona/AVCP-Xml] Colelgamento azienda aggiudicataria su gara (#33)

 

Ok, 
qui c'è un mio sbaglio nella stampa dell'errore; sostituisca il file app/model/garaPartecipanti.php con quello che le invio e riprovi ad inserire la ditta.
Dovrebbe fallire ancora, ma almeno adesso vedrà il perché. 

Mi faccia sapere cosa le dice e mi rimandi il log col nuovo errore.

PS - Ha provato a cancellare la gara e a reinserirla?


-----------------------------------------
Claudio Roncaglio
Ufficio per le Relazioni con il Pubblico
della Provincia di Cremona 
C.so Vittorio Emanuele II,17
tel. +39 0372 406247 fax +39 0372 406301
-----------------------------------------

----- Messaggio originale -----
Da: "cedgarbagnate" <notifications@github.com>
A: "provinciadicremona" <AVCP-Xml@noreply.github.com>
Cc: "ProvinciaCremona" <github@provincia.cremona.it>, "Comment" <comment@noreply.github.com>
Inviato: Giovedì, 30 gennaio 2020 11:15:48
Oggetto: Re: [provinciadicremona/AVCP-Xml] Colelgamento azienda aggiudicataria su gara (#33)

Di seguito troverete i log richiesti
[Thu Jan 30 10:40:40.595375 2020] [php7:error] [pid 28800] [client 93.57.27.68:51473] PHP Fatal error: Uncaught Error: Call to undefined function mysql_error() in /var/www/avcp/AVCP_GARMIL/site/app/model/garaPartecipanti.php:207 Stack trace: #0 /var/www/avcp/AVCP_GARMIL/site/app/controller/garaController.php(25): require_once() #1 /var/www/avcp/AVCP_GARMIL/site/app/controller/indexController.php(24): require_once('/var/www/avcp/A...') #2 /var/www/avcp/AVCP_GARMIL/site/index.php(45): require_once('/var/www/avcp/A...') #3 {main} thrown in /var/www/avcp/AVCP_GARMIL/site/app/model/garaPartecipanti.php on line 207, referer: http://xml.comune.garbagnate-milanese.mi.it/?mask=ditta&do=cercaDitta&id=2903


Informazioni sull'installazione del programma AVCP-Xml:

Versione di AVCP-Xml [0.9.0]
Sistema Operativo: [Linux]
Versione di Apache [Server version: Apache/2.4.25 (Debian)]
Versione di MySQL [Ver 15.1 Distrib 10.1.37-MariaDB]
Versione di PHP [PHP 7.3.1]
Browser [tutti]
