### ISSUE TITLE
Oggetto della gara

### ISSUE THREAD

**Issue by valeriofontana** [provinciadicremona/AVCP-Xml#35]
Salve, ho notato che durante l'inserimento della gara, nella sezione "Oggetto" all'interno della casella di scrittura, c'è un refuso "Oggeto della gara".
![Screenshot (8)_LI](https://user-images.githubusercontent.com/60922468/74230734-477f1300-4cc5-11ea-8460-f0dd66f12d13.jpg)

**Comment by ProvinciaCremona** [comment]
Grazie della segnalazione!


-----------------------------------------
Claudio Roncaglio
Ufficio per le Relazioni con il Pubblico
della Provincia di Cremona 
C.so Vittorio Emanuele II,17
tel. +39 0372 406247 fax +39 0372 406301
-----------------------------------------

----- Messaggio originale -----
Da: "valeriofontana" <notifications@github.com>
A: "provinciadicremona" <AVCP-Xml@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Inviato: Martedì, 11 febbraio 2020 11:54:49
Oggetto: [provinciadicremona/AVCP-Xml] Oggetto della gara (#35)

Salve, ho notato che durante l'inserimento della gara, nella sezione "Oggetto" all'interno della casella di scrittura, c'è un refuso "Oggeto della gara".

![Screenshot (8)_LI](https://user-images.githubusercontent.com/60922468/74230734-477f1300-4cc5-11ea-8460-f0dd66f12d13.jpg)





-- 

You are receiving this because you are subscribed to this thread.

Reply to this email directly or view it on GitHub:

https://github.com/provinciadicremona/AVCP-Xml/issues/35

**Comment by valeriofontana** [comment]
Grazie a lei Claudio, con il suo contributo ha semplificato il nostro lavoro. Buona giornata
